# Generated by Django 3.2.7 on 2022-06-06 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220606_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=100)),
                ('passport_fin', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='documents/')),
                ('voen', models.CharField(max_length=100)),
                ('staff_count', models.IntegerField()),
                ('company_sector', models.CharField(max_length=100)),
                ('bank_rekvizit', models.FileField(upload_to='rekvizits/')),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expences', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
