# Generated by Django 3.2.7 on 2022-06-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220620_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
