# Generated by Django 3.2.7 on 2022-07-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='life_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_work_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='premia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='vacation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
