# Generated by Django 3.2.7 on 2022-07-22 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_workcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('document', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DocumentExample',
                'verbose_name_plural': 'DocumentExamples',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('document_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.documentexample')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Document',
            },
        ),
    ]
