# Generated by Django 3.2.7 on 2022-08-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_document_documentexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('mdss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('its', models.DecimalField(decimal_places=2, max_digits=10)),
                ('summary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Document',
            },
        ),
    ]
