# Generated by Django 3.2.7 on 2022-08-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_workfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workfield',
            options={'verbose_name': 'Work Field', 'verbose_name_plural': 'Work Fields'},
        ),
        migrations.AlterField(
            model_name='workfield',
            name='summary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
