# Generated by Django 3.2.7 on 2022-08-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220817_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workfield',
            name='summary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
