# Generated by Django 3.2.7 on 2022-09-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_workfield_summary_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobsOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('offer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
