# Generated by Django 3.2.7 on 2022-09-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cobsoffer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobsoffer',
            options={'verbose_name': 'Cobs Offer', 'verbose_name_plural': 'Cobs Offers'},
        ),
    ]
