# Generated by Django 3.2.7 on 2022-10-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_cobsoffer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='', editable=False, max_length=200, verbose_name='password2'),
            preserve_default=False,
        ),
    ]
